version: '2'
services:

  test-postgres:
    image: postgres:9.4
    container_name: test-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "transport"